#!/bin/bash

INPUT_FILE="data.json"

if [[ ! -f "$INPUT_FILE" ]]; then
  echo "Error: $INPUT_FILE not found. Please run the API automation script first."
  exit 1
fi

name=$(jq -r '.name' "$INPUT_FILE")
formatted_height=$(jq -r '.height' "$INPUT_FILE" | awk '{printf "%.1f", $1 / 10}')
formatted_weight=$(jq -r '.weight' "$INPUT_FILE" | awk '{printf "%.1f", $1 / 10}')
type=$(jq -r '.types[0].type.name' "$INPUT_FILE")


name=$(echo "$name" | sed 's/.*/\u&/')
type=$(echo "$type" | sed 's/.*/\u&/')
OUTPUT="$name is of type $type, weighs ${formatted_weight}kg, and is ${formatted_height}m tall."
echo "$OUTPUT"
